export const AUTHENTIFICATION = 'AUTHENTIFICATION';
export const AUTHENTIFICATION_SUCCESS = 'AUTHENTIFICATION_SUCCESS';
export const AUTHENTIFICATION_ERROR = 'AUTHENTIFICATION_ERROR';
export const LOGOUT = 'LOGOUT';
export const TOGGLE_NETWORK_STATE = 'TOGGLE_NETWORK_STATE';
